ARG PYTHON_VERSION

FROM python:${PYTHON_VERSION}-stretch

WORKDIR /app

COPY requirements/ /app/requirements/
RUN pip install tox

COPY src/ /app/src/
COPY tests/ /app/tests/
COPY MANIFEST.in pyproject.toml setup.py tox.ini /app/
