const { createTransformer } = require('babel-jest');

// from process.env.JEST_BABEL_OPTIONS that is present after neutrino().jest() is called
// matches webpack babel-loader module rule
// previously auto-generated by: https://github.com/neutrinojs/neutrino/blob/f9d476446983684225545159f58bbed2a93ca824/packages/jest/src/index.js#L37
const jestBabelOptions = {
  babelrc: false,
  configFile: false,
  presets: [
    [
      "@babel/preset-env",
      {
        debug: false,
        useBuiltIns: false,
        shippedProposals: true,
        targets: {
          browsers: [
            "last 2 Chrome versions",
            "last 2 Firefox versions",
            "last 2 Edge versions",
            "last 2 Opera versions",
            "last 2 Safari versions",
            "last 2 iOS versions"
          ]
        }
      }
    ],
    [
      "@babel/preset-react",
      {
        development: true,
        useSpread: true
      }
    ]
  ],
  plugins: [
    "@babel/plugin-syntax-dynamic-import",
    "react-hot-loader/babel",
  ]
}

module.exports = createTransformer(jestBabelOptions);
