#!/usr/bin/env bash

set -o errexit -o pipefail

export AWS_ACCESS_KEY_ID=$(curl ${TC_SECRET_URL} | python3 -c 'import json, sys; a = json.load(sys.stdin); print(a["secret"]["aws_access_key"])')
export AWS_SECRET_ACCESS_KEY=$(curl ${TC_SECRET_URL} | python3 -c 'import json, sys; a = json.load(sys.stdin); print(a["secret"]["aws_secret_key"])')


cp scripts/404.html public/404.html

aws s3 sync \
    --metadata "{
    \"Strict-Transport-Security\": \"max-age=31536000\",
    \"Access-Control-Allow-Origin\": \"*\",
    \"x-content-type-options\": \"nosniff\",
    \"x-frame-options\": \"SAMEORIGIN\",
    \"x-xss-protection\": \"1; mode=block\"
}" \
    --metadata-directive "REPLACE" \
    --cache-control "max-age=300" \
    --delete \
    ./public/ "s3://${WEBSITE_BUCKET}/"
