#!/usr/bin/env bash

set -o errexit -o pipefail
set -e

export AWS_ACCESS_KEY_ID=$(curl ${AWS_CREDENTIALS_SECRET} | python3 -c 'import json, sys; a = json.load(sys.stdin); print(a["secret"]["aws_access_key"])')
export AWS_SECRET_ACCESS_KEY=$(curl ${AWS_CREDENTIALS_SECRET} | python3 -c 'import json, sys; a = json.load(sys.stdin); print(a["secret"]["aws_secret_key"])')

# Grab app config and convert it to shell format
curl "${APP_CONFIG_SECRET}" | python3 -c 'import json, sys; a = json.load(sys.stdin); [print("{}={}".format(k, v)) for k,v in a["secret"].items()]' > .env

yarn build

cp scripts/404.html build/404.html

aws s3 sync \
    --metadata "{
    \"Strict-Transport-Security\": \"max-age=31536000\",
    \"Access-Control-Allow-Origin\": \"*\",
    \"x-content-type-options\": \"nosniff\",
    \"x-frame-options\": \"SAMEORIGIN\",
    \"x-xss-protection\": \"1; mode=block\"
}" \
    --metadata-directive "REPLACE" \
    --cache-control "max-age=300" \
    --delete \
    ./build/ "s3://${WEBSITE_BUCKET}/"
