# update all packages, unless marked with "pyup: ignore" in the requirements file
update: all

# enabling version pinning
pin: True

branch: master

# automatically discover requirements files
search: True

# in time for a mid-week release
schedule: every week on monday
