version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.13"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync --group=docs --no-dev
    - uv run -m sphinx -T -b html -d docs/_build/doctrees -D language=en docs/source $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/source/conf.py
