version: 0
allowPullRequests: public
metadata:
  name: Balrog
  description: Balrog CI Tasks
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 1200
      image: "rail/python-test-runner"
      env:
        NO_VOLUME_MOUNT: 1
      command:
        - "/bin/bash"
        - "-c"
        - "git clone $GITHUB_HEAD_REPO_URL && cd balrog && git checkout $GITHUB_HEAD_BRANCH && bash run-tests.sh backend"
      features:
        dind: true
        taskclusterProxy: true
    extra:
      github:
        env: true
        events:
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
          - push
    metadata:
      name: Balrog back-end tests
      description: Balrog Python tests
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"

  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 1200
      image: "rail/python-test-runner"
      env:
        NO_VOLUME_MOUNT: 1
      command:
        - "/bin/bash"
        - "-c"
        - "git clone $GITHUB_HEAD_REPO_URL && cd balrog && git checkout $GITHUB_HEAD_BRANCH && bash run-tests.sh frontend"
      features:
        dind: true
    extra:
      github:
        env: true
        events:
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
          - push
    metadata:
      name: Balrog front-end tests
      description: Balrog JavaScript tests
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"

  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 1200
      image: "rail/python-test-runner"
      env:
        NO_VOLUME_MOUNT: 1
      command:
        - "/bin/bash"
        - "-c"
        - "git clone $GITHUB_HEAD_REPO_URL && cd balrog && git checkout $GITHUB_HEAD_BRANCH && cd agent && bash run-tests.sh"
      features:
        dind: true
    extra:
      github:
        env: true
        events:
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
          - push
    metadata:
      name: Balrog Agent Tests
      description: Balrog Agent Tests
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"

# TODO: make this depend on the test task after https://bugzilla.mozilla.org/show_bug.cgi?id=1252144 is fixed
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    scopes:
      - secrets:get:repo:github.com/mozilla/balrog:dockerhub
    payload:
      maxRunTime: 3600
      image: "taskcluster/image_builder:0.1.3"
      features:
        dind: true
        taskclusterProxy: true
      command:
        - "/bin/bash"
        - "-c"
        - "git clone $GITHUB_HEAD_REPO_URL && cd balrog && git checkout $GITHUB_HEAD_BRANCH && scripts/push-dockerimage.sh"
    extra:
      github:
        env: true
        events:
          - push
        branches:
          - master
    metadata:
      name: Balrog Docker Image Creation
      description: Balrog Docker Image Creation
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"

  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 1200
      image: "rail/python-test-runner"
      env:
        NO_VOLUME_MOUNT: 1
      command:
        - "/bin/bash"
        - "-c"
        - "git clone $GITHUB_HEAD_REPO_URL && cd balrog && git checkout $GITHUB_HEAD_BRANCH && cd client && bash run-tests.sh"
      features:
        dind: true
    extra:
      github:
        env: true
        events:
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
          - push
    metadata:
      name: Balrog Python Client Tests
      description: Balrog Python Client Tests
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"


# TODO: make this depend on the test task after https://bugzilla.mozilla.org/show_bug.cgi?id=1252144 is fixed
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    scopes:
      - secrets:get:repo:github.com/mozilla/balrog:dockerhub
    payload:
      maxRunTime: 3600
      image: "taskcluster/image_builder:0.1.3"
      features:
        dind: true
        taskclusterProxy: true
      command:
        - "/bin/bash"
        - "-c"
        - "git clone $GITHUB_HEAD_REPO_URL && cd balrog/agent && git checkout $GITHUB_HEAD_BRANCH && scripts/push-dockerimage.sh"
    extra:
      github:
        env: true
        events:
          - push
        branches:
          - master
    metadata:
      name: Balrog Docker Image Creation
      description: Balrog Docker Image Creation
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"

# TODO: make this depend on the test task after https://bugzilla.mozilla.org/show_bug.cgi?id=1252144 is fixed
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    scopes:
      - secrets:get:repo:github.com/mozilla/balrog:dockerhub
    payload:
      maxRunTime: 3600
      image: "taskcluster/image_builder:0.1.3"
      features:
        dind: true
        taskclusterProxy: true
      command:
        - "/bin/bash"
        - "-c"
        - "git clone -b {{ event.version }} {{ event.head.repo.url }} && cd balrog && scripts/push-dockerimage.sh"
    extra:
      github:
        env: true
        events:
          - release
    metadata:
      name: Balrog Docker Image Creation (release event)
      description: Balrog Docker Image Creation (release event)
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"

# TODO: make this depend on the test task after https://bugzilla.mozilla.org/show_bug.cgi?id=1252144 is fixed
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    scopes:
      - secrets:get:repo:github.com/mozilla/balrog:dockerhub
    payload:
      maxRunTime: 3600
      image: "taskcluster/image_builder:0.1.3"
      features:
        dind: true
        taskclusterProxy: true
      command:
        - "/bin/bash"
        - "-c"
        - "git clone -b {{ event.version }} {{ event.head.repo.url }} && cd balrog/agent && scripts/push-dockerimage.sh"
    extra:
      github:
        env: true
        events:
          - release
    metadata:
      name: Balrog Agent Docker Image Creation (release event)
      description: Balrog Agent Docker Image Creation (release event)
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
