FROM mysql:8.0-debian@sha256:7acd9677ba9d3d1c91a3b2a7999e182ca15919c5f2577184e5c8ce5384867ade

# netcat is used to listen to the ports.

RUN apt-get -q update \
    && apt-get -q --yes install netcat-traditional pkg-config \
    && apt-get clean

# Lower error logging to get rid of health check spam
RUN ["/bin/bash", "-c", "echo '[mysqld]\nlog_error_verbosity=2' > /etc/mysql/conf.d/errors.cnf"]
