# Should match the version used in production
FROM nginx:1.31@sha256:5aca99593157f4ae539a5dec1092a0ad8762f8e2eb1789085a13a0f5622369f6

RUN apt-get -q update \
    && apt-get -q --yes install ncat \
    && apt-get clean
