FROM mysql:8.0-debian@sha256:9382e4f6f7f013231049ab854de9d0810594d028f4237b67102acc7ade8e3a99

# netcat is used to listen to the ports.

RUN apt-get -q update \
    && apt-get -q --yes install netcat-traditional pkg-config \
    && apt-get clean

# Lower error logging to get rid of health check spam
RUN ["/bin/bash", "-c", "echo '[mysqld]\nlog_error_verbosity=2' > /etc/mysql/conf.d/errors.cnf"]
