# Should match the version used in production
FROM nginx:1.29@sha256:b17697e86d0c02378716277d09f45b946f8709aaa12c708e30fdd4736f536af1

RUN apt-get -q update \
    && apt-get -q --yes install ncat \
    && apt-get clean
