FROM python:3.7-slim

MAINTAINER bhearsum@mozilla.com

RUN apt-get -q update
RUN apt-get -q --yes install default-libmysqlclient-dev mysql-client gcc git

WORKDIR /app

COPY requirements-tox.txt /app/
RUN pip install -r requirements-tox.txt

COPY aus-data-snapshots/ /app/aus-data-snapshots/
COPY auslib/ /app/auslib/
COPY scripts/ /app/scripts/
COPY uwsgi/ /app/uwsgi/
COPY MANIFEST.in requirements.txt requirements-test.txt setup.py tox.ini version.txt /app/
