FROM mysql:8.0-debian@sha256:e90eaf1db3a7032d0dd1ea78141014f173eaeba62229a96124228df653e2db96

# netcat is used to listen to the ports.

RUN apt-get -q update \
    && apt-get -q --yes install netcat-traditional pkg-config \
    && apt-get clean

# Lower error logging to get rid of health check spam
RUN ["/bin/bash", "-c", "echo '[mysqld]\nlog_error_verbosity=2' > /etc/mysql/conf.d/errors.cnf"]
