parameters:
  productParam:
    name: product
    in: query
    description: Name of the product to filter the rules/releases against.
    type: string
    x-nullable: true
    required: false

  productPathParam:
    name: product
    in: path
    description: Name of the product.
    type: string
    required: true

  channelQueryParam:
    name: channel
    in: query
    description: Name of the channel to filter.
    type: string
    x-nullable: true
    required: false

  channelPathParam:
    name: channel
    in: path
    description: Release channel.
    type: string
    required: true

  releaseParam:
    name: release
    in: path
    description: release name
    type: string
    maxLength: 100
    required: true
  
  pretty:
    name: pretty
    in: query
    description: "If 'pretty' is present in the query string and set to true, it will be pretty formatted."
    type: string
    x-nullable: true
    required: false

  pageParam:
    name: page
    in: query
    description: Variable value used pagination of response revisions.
    type: integer
    minimum: 1
    x-nullable: true
    required: false

  limitParam:
    name: limit
    in: query
    description: Variable value used for calculating offset for pagination.
    type: integer
    minimum: 1
    x-nullable: true
    required: false

  platformParam:
    name: platform
    in: path
    description: platform name
    type: string
    required: true

  localeParam:
    name: locale
    in: path
    description: locale identifier
    type: string
    required: true

  rule_id_or_alias_param:
    name: id_or_alias
    in: path
    description: rule_id or alias field value to update the rule against
    type: string
    required: true

  rule_id_param:
    name: rule_id
    in: path
    description: Field value to uniquely identfiy the rule
    type: integer
    minimum: 0
    required: true
