[tox]
envlist = py313

[testenv]
depends = clean
setenv =
    PYTHONDONTWRITEBYTECODE=1
    HYPOTHESIS_STORAGE_DIRECTORY=/tmp
runner = uv-venv-lock-runner
package = editable
commands =
    {posargs:py.test -n auto --cov-config=tox.ini --cov-append --cov=balrogagent --cov-report term-missing tests}

[testenv:clean]
skip_install = true
commands = coverage erase
depends =

[testenv:report]
skip_install = true
commands = coverage report -m
depends = py313
parallel_show_output = true

[testenv:check]
skip_install = true
commands =
    ruff format --diff {toxinidir}
    isort --check --diff {toxinidir}
    flake8 {toxinidir}
# Doesn't work without a .git directory
#    check-manifest -v {toxinidir}

[flake8]
max-line-length = 160
exclude = .ropeproject,.tox,sandbox,build
show-source = True
# W503 is a default ignore, but gets overridden when we set this, so we need
# to add it again ourselves.
ignore = W503

[pytest]
norecursedirs = .tox .git .hg sandbox build
python_files = test_*.py

[coverage:run]
branch = true
source = balrogagent

[coverage:paths]
source =
  src/
  .tox/*/lib/python*/site-packages/

[coverage:report]
show_missing = True
