openapi: 3.0.0
info:
  title: Balrog Admin API
  description: Balrog Admin API
  version: 2.0.0

paths:
  /releases:
    get:
      summary: Get a list of basic information about Releases in Balrog's database
      operationId: auslib.web.admin.views.releases_v2.get_releases
      responses:
        '200':
          description: List of Releases
          content:
            application/json:
              schema:
                type: object
                required:
                  - releases
                properties:
                  releases:
                    type: array
                    items:
                      type: object
                      required:
                        - name
                        - rule_info
                      properties:
                        name:
                          type: string
                        product:
                          type: string
                          nullable: true
                        data_version:
                          type: number
                          nullable: true
                        read_only:
                          type: boolean
                          nullable: true
                        rule_info:
                          type: object
                          properties:
                            ^.*$:
                              type: object
                              required:
                                - product
                                - channel
                              properties:
                                product:
                                  type: string
                                  nullable: true
                                channel:
                                  type: string
                                  nullable: true
                        scheduled_changes:
                          type: array
                          items:
                            type: object
                            required:
                              - name
                              - data_version
                              - sc_id
                              - when
                              - change_type
                              - scheduled_by
                              - sc_data_version
                              - complete
                            properties:
                              name:
                                type: string
                              path:
                                type: string
                              product:
                                type: string
                              data_version:
                                type: number
                              read_only:
                                type: boolean
                              rule_info:
                                type: object
                              sc_id:
                                type: number
                              when:
                                type: number
                              change_type:
                                type: string
                                enum:
                                  - insert
                                  - update
                                  - delete
                              scheduled_by:
                                type: string
                              sc_data_version:
                                type: number
                              complete:
                                type: boolean

  /releases/{name}:
    get:
      summary: Get a Release blob and data versions
      operationId: auslib.web.admin.views.releases_v2.get_release
      parameters:
        - name: name
          in: path
          required: true
          description: Release name
          schema:
            type: string
      responses:
        '200':
          description: Release blob and data versions
          content:
            application/json:
              schema:
                type: object
                required:
                  - blob
                  - data_versions
                properties:
                  blob:
                    type: object
                  data_versions:
                    type: object
        '404':
          description: Release not found

    post:
      summary: Update part of a Release
      operationId: auslib.web.admin.views.releases_v2.update_release
      parameters:
        - name: name
          in: path
          required: true
          description: Release name
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - blob
                - old_data_versions
              properties:
                blob:
                  type: object
                old_data_versions:
                  type: object
                # Creates a scheduled change if passed
                when:
                  type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Client error
        '404':
          description: Release does not exist

    put:
      summary: Overwrites an entire release
      operationId: auslib.web.admin.views.releases_v2.set_release
      parameters:
        - name: name
          in: path
          required: true
          description: Release name
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - blob
              properties:
                blob:
                  type: object
                # Optional in this endpoint, because the Release may not yet exist.
                # The view is responsible for ensuring this exists if the Release does.
                old_data_versions:
                  type: object
                # Required if the Release doesn't yet exist.
                product:
                  type: string
                # Creates a scheduled change if passed
                when:
                  type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Client error

    delete:
      summary: Delete an entire Release
      operationId: auslib.web.admin.views.releases_v2.delete_release
      parameters:
        - name: name
          in: path
          required: true
          description: Release name
          schema:
            type: string
      responses:
        '200':
          description: OK
        '400':
          description: Client error
        '403':
          description: Permission denied
        '404':
          description: Release does not exist
